### ISSUE TITLE
LZF in QGIS 3.30

### ISSUE THREAD

**Issue by EZUSoft** [kreis-viersen/xplan-reader#6]
In QGIS 3.30 kommt es zu einem zum Fehler:
```
Traceback (most recent call last):
  File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\xplan-reader\xplan_reader.py", line 458, in importXplanGml
    addXplanLayer('BP_Plan', 'Flaeche')
  File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\xplan-reader\xplan_reader.py", line 250, in addXplanLayer
    geom = geom.convexHull().convertToType(1).simplify(5)
TypeError: QgsGeometry.convertToType(): argument 1 has unexpected type 'int'
```

Meiner Meinung nach müsste das so angepasst werden:
```
from qgis.core import Qgis, QgsExpression, QgsExpressionContextUtils, QgsFeatureRequest, QgsMessageLog, QgsProject, QgsRectangle, QgsVectorLayer, QgsWkbTypes

# ........

geom = geom.convexHull().convertToType(QgsWkbTypes.LineGeometry).simplify(5)
```

OT: Danke, dass ihr die Initiative ergriffen habt :-)

**Comment by EZUSoft** [comment]
...nein eher nicht.
Bin "Alleinentwicker" und habe noch zu wenig Erfahrung mit github :-)

**Comment by pathmapper** [comment]
Alles klar, noch einmal vielen Dank!
